import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './custom.scss';
import { GoogleOAuthProvider } from "@react-oauth/google";
import { AuthProvider } from "./AuthContext";
import ProtectedRoute from "./components/ProtectedRoute"
import TopHeader from "./components/TopHeader"
// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root Layout
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleOAuthProvider clientId="325790879889-ve0qa2du4ot9b4nr6v4kgbsg6nvl4kfi.apps.googleusercontent.com">
           <AuthProvider>
            {/* uvicorn backend1.asgi:application --reload 
            celery -A backend1 worker -l info -P solo
            */}
            {/* Global sidebar drawer visible on all pages */}
            {/* Global top header with LNMIIT logo (left) and profile icon (right) */}
            <TopHeader />
            <ProtectedRoute>
              {children}
            </ProtectedRoute>
          </AuthProvider>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
